added models for refresh token configuration
auth0/auth0.net pull request #451
Opened 2020-11-13 09:16 UTC by SamTheWizard

### Changes

I added new models for the refresh token rotation. With the changes it should be possible to configure
refresh token settings on create and update of clients.

This is important, because at the moment it is impossible to configure a client for refresh token rotation.

### References

I added the properties as described in the api documentation: https://auth0.com/docs/api/management/v2?utm_source=emea-google-dg&utm_medium=cpc&utm_campaign=Branded&utm_content=dynamicRT2&utm_term=&gclid=Cj0KCQiA-rj9BRCAARIsANB_4ADez090wM_osbvalReSynvXe2yRi80CsGig9CxckDToVUFjizzbPukaAnZ3EALw_wcB#!/Clients/post_clients

### Testing

I was not able to run integration tests, because i do not have a tenant to use.

- [ ] This change adds unit test coverage

- [ ] This change adds integration test coverage

- [ ] This change has been tested on the latest version of the platform/language or why not

### Checklist

- [x ] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)

- [x ] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)

- [ ] All existing and new tests complete without errors

2020-11-13 09:36 UTC, frederikprijck requested changes
Thanks for this PR. I added a few comments, But we will also need some integration tests for this to ensure it works as expected.

Keep in mind that this change affects the following calls:

- GetAllAsync: https://github.com/auth0/auth0.net/blob/master/src/Auth0.ManagementApi/Clients/ClientsClient.cs#L56
- GetAsync: https://github.com/auth0/auth0.net/blob/master/src/Auth0.ManagementApi/Clients/ClientsClient.cs#L93
- CreateAsync: https://github.com/auth0/auth0.net/blob/master/src/Auth0.ManagementApi/Clients/ClientsClient.cs#L35
- UpdateAsync: https://github.com/auth0/auth0.net/blob/master/src/Auth0.ManagementApi/Clients/ClientsClient.cs#L119

2020-11-13 09:36 UTC, frederikprijck commented on src/Auth0.ManagementApi/Models/ClientBase.cs
> +        /// </summary>
We will need a summary here

2020-11-13 09:36 UTC, frederikprijck commented on src/Auth0.ManagementApi/Models/RefreshToken.cs
> +        public RefreshTokenExpirationType ExpirationType { get; set; } = RefreshTokenExpirationType.NonExpiring;
I don't think the above default values are a good idea. They are the least secure options and I do not think we should use them as default values.

I would remove any default but instead enforce the need to specify both of these properties when passing RefreshToken.

2020-11-13 15:49 UTC, frederikprijck approved these changes

2020-11-13 15:53 UTC, frederikprijck commented
@SamTheWizard Thanks for this PR. I pushed a change to the tests and made sure the tests run successfully (they also ran successfully with your changes, but I removed some duplication)

2020-11-13 16:07 UTC, merged

2020-11-13 16:20 UTC, frederikprijck commented
Fixes 450

2020-11-16 07:20 UTC, jonasaebersold commented
It only took about seven hours from the new reported issue to the finished nuget package. It is not our expectation that it always goes that fast. This message is just an appreciation, it's very impressive! Thank you very much for the quick and great support.