Update UserCreateRequest password property xml documentation
auth0/auth0.net pull request #497
Opened 2021-04-26 19:20 UTC by Goolyio

Issue: #496 

Updated the password property XML documentation summary to include email as a non mandatory connection type.

2021-05-05 07:13 UTC, frederikprijck commented
As mentioned in https://github.com/auth0/auth0.net/issues/496, holding off on reviewing until the API docs are updated.

2021-08-18 08:24 UTC, frederikprijck requested changes
Sorry for taking so long. I went and asked to get this resolved on the docs side and managed to get things progressing.

2021-08-18 08:24 UTC, frederikprijck commented on src/Auth0.ManagementApi/Models/UserCreateRequest.cs
> +        /// Gets or sets the user's password. This is mandatory on non SMS or email connections.
Soon the docs will contain the following:

> Initial password for this user (mandatory only for auth0 connection strategy).

So lets update this to be:

```suggestion
/// Gets or sets the user's password. This is mandatory only for auth0 connection strategy.
```

2021-08-18 08:25 UTC, frederikprijck approved these changes

2021-08-18 09:19 UTC, Goolyio commented
> Sorry for taking so long. I went and asked to get this resolved on the docs side and managed to get things progressing.

NW I like your commit, makes a lot of sense. What are the next steps to getting this merged, is there anything you need from me?

2021-08-18 09:24 UTC, frederikprijck commented
@Goolyio Nope, All is fine. Will merge it somewhere today.  Thanks again for the patience and the initial PR!

2021-08-18 09:42 UTC, merged