Features/rules configs management client
auth0/auth0.net pull request #552
Opened 2022-02-24 17:00 UTC by caldwell0414

### Changes

Added a new Client implementation to the ManagementApi named RulesConfigClient.  This client will make calls to the /rules-configs endpoint in the Auth0 Management API (v2).  It includes a PUT and a DELETE call.  It does not include any GET requests because they are not supported on that endpoint for security purposes.  Because the implementor cannot determine if a variable already exists, we have named the PUT implementation CreateOrUpdateAsync().

We followed the pattern provided for other clients in the library and included the great cleanup work done by @frederikprijck.  His commit is included in our PR, so you may want to accept his first.

### References

See Issue #551 for more details.

### Testing

Our PR includes integration tests to exercise the new client.

- [ ] This change adds unit test coverage

- [x] This change adds integration test coverage

- [x] This change has been tested on the latest version of the platform/language or why not

### Checklist

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)

- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)

- [ ] All existing and new tests complete without errors
       NOTE: some tests require configuration that we don't have correct on our test host.  please let us know if your testing runs into any critical failures.  We did not modify any existing code and so do not expect any side effects.

2022-02-28 08:39 UTC, frederikprijck commented
Thanks for this!

Let me first merge https://github.com/auth0/auth0.net/pull/550, then we can rebase your branch and get it reviewed and merged as well.

2022-02-28 14:50 UTC, caldwell0414 commented
Thanks very much.  Please let me know if you need anything.  I’ve been using Auth0 for a long time and I’m happy to be able to contribute.

jc

From: Frederik Prijck ***@***.***>
Sent: Monday, February 28, 2022 3:40 AM
To: auth0/auth0.net ***@***.***>
Cc: James Caldwell ***@***.***>; Author ***@***.***>
Subject: Re: [auth0/auth0.net] Features/rules configs management client (PR #552)


Thanks for this!

Let me first merge #550<https://github.com/auth0/auth0.net/pull/550>, then we can rebase your branch and get it reviewed and merged as well.

—
Reply to this email directly, view it on GitHub<https://github.com/auth0/auth0.net/pull/552#issuecomment-1054016385>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ATA3OEXUT42U3T2OW7RCBETU5MYETANCNFSM5PH6CNEQ>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

2022-03-02 11:04 UTC, frederikprijck commented
Hey @caldwell0414 ,

Would you be able to resolve the conflicts? I just merged the other PR so you should be able to drop the cleanup commit, and merge in master.

Thanks

2022-03-04 11:27 UTC, frederikprijck requested changes

2022-03-04 11:27 UTC, frederikprijck commented on src/Auth0.ManagementApi/Clients/RulesConfigClient.cs
> +        /// <param name="request">The <see cref="RuleCreateRequest" /> containing the details of the rule to create.</param>
```suggestion
        /// <param name="request">The <see cref="RulesConfigCreateOrUpdateRequest" /> containing the details of the rule to create or update.</param>
```

2022-03-04 11:27 UTC, frederikprijck approved these changes

2022-03-04 11:28 UTC, frederikprijck commented
I update the base here, thanks! 🚀

2022-03-04 11:34 UTC, merged