Add ProvisioningTicketUrl
auth0/auth0.net pull request #562
Opened 2022-04-26 00:15 UTC by zzanol

Added ProvisioningTicketUrl to Connection class.  ProvisioningTicketUrl (provisioning_ticket_url) is returned when getting connections of with specific strategies, including 'google-apps'.

2022-04-27 07:25 UTC, frederikprijck requested changes

2022-04-27 07:25 UTC, frederikprijck commented on src/Auth0.ManagementApi/Models/Connection.cs
> +        /// The provisioning ticket URL
```suggestion
        /// The provisioning ticket URL for AD / LDAP connections
```

2022-04-27 07:28 UTC, frederikprijck commented
Thanks for the PR, added a small comment but happy to merge once resolved.

2022-04-27 16:35 UTC, zzanol commented on src/Auth0.ManagementApi/Models/Connection.cs
> +        /// The provisioning ticket URL
Done, thank you

2022-04-27 19:07 UTC, frederikprijck approved these changes

2022-04-29 15:32 UTC, zzanol commented
Anything else needed to get this merged?

2022-04-29 15:40 UTC, merged

2022-04-29 15:43 UTC, frederikprijck commented
No, sorry about that. Thanks for the PR. Will see to cut a release soon, might need to see if we need to incorporate the other open PR's first.