added generic get/set metadata methods on UserBase
auth0/auth0.net pull request #646
Opened 2023-08-17 11:44 UTC by MichaelPruefer

### Changes

Added generic methods to get/set user metadata, e.g.:
`userInstance.getAppMetadata<MyAppMetadata>();`
`userInstance.getUserMetadata<MyUserMetadata>();`
`userInstance.setAppMetadata(myAppMetadata);`
`userInstance.setUserMetadata(myUserMetadata);`

As for now Newtonsoft.Json.Linq.JObject is used as this type seems to be deserialized when reading users.

Auth0.ManagementApi.Models.UserBase
- added new generic get/set methods for AppMetadata and UserMetadata

Auth0.ManagementApi.IntegrationTests.UsersTests:
- added test for read/write user metadata with new generic get/set methods

### References
#645 

### Testing
Retrieve a user with AppMetadata, call getAppMetadata with a matching type and see the filled properties

- [x] This change adds unit test coverage

- [x] This change adds integration test coverage

- [ ] This change has been tested on the latest version of the platform/language or why not
I'm unable to run the tests as configuration seems missing

### Checklist

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)

- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)

- [ ] All existing and new tests complete without errors
I'm unable to run the tests as configuration seems missing

2023-08-17 12:58 UTC, frederikprijck requested changes
Thanks for the PR, left some comments

2023-08-17 12:58 UTC, frederikprijck commented on tests/Auth0.ManagementApi.IntegrationTests/UsersTests.cs
> +        }
Can we update this test to use Set, then call Auth0 to create the user, then use Get to verify it gets serialized and send correctly?

2023-08-17 12:58 UTC, frederikprijck commented on src/Auth0.ManagementApi/Models/UserBase.cs
> +            UserMetadata = JObject.FromObject(userMetadata);
Should we ensure T is an object?

2023-08-17 12:58 UTC, frederikprijck commented on src/Auth0.ManagementApi/Models/UserBase.cs
> +            AppMetadata = JObject.FromObject(appMetadata);
Should we ensure T is an object?

2023-08-17 12:58 UTC, frederikprijck commented on src/Auth0.ManagementApi/Models/UserBase.cs
> +            throw new ArgumentException("Unknown metadata type");
I would just return null here and drop the first part that returns default. Default can be useful when we support more than just objects, but given it has to be an object, I guess we can use null for simplicity.

Having said that, Should we ensure T is an object?

2023-08-17 12:58 UTC, frederikprijck commented on src/Auth0.ManagementApi/Models/UserBase.cs
> +            throw new ArgumentException("Unknown metadata type");
I would just return null here and drop the first part that returns default. Default can be useful when we support more than just objects, but given it has to be an object, I guess we can use null for simplicity.

Having said that, Should we ensure T is an object?

2023-08-21 09:07 UTC, frederikprijck requested changes

2023-08-21 09:07 UTC, frederikprijck commented on src/Auth0.ManagementApi/Models/UserBase.cs
> +        /// <exception cref="ArgumentException"></exception>
We no longer throw this exception.

2023-08-21 09:07 UTC, frederikprijck commented on src/Auth0.ManagementApi/Models/UserBase.cs
> +        /// <exception cref="ArgumentException"></exception>
We no longer throw this exception.

2023-08-23 08:11 UTC, MichaelPruefer commented
I removed the incorrect exception documentation

2023-08-23 08:29 UTC, frederikprijck approved these changes
Thanks for the PR. I pushed a commit to fix the tests.

2023-08-23 08:39 UTC, merged