Fixes issue where SendInvitationEmail is not defaulting to True
auth0/auth0.net pull request #728
Opened 2024-09-19 08:43 UTC by kailash-b

### Changes

Ensured the default value for `OrganizationCreateInvitationRequest.SendInvitationEmail` to `True`

### References

Please include relevant links supporting this change such as a:

Refer #727 for more details.

### Testing

- [x] This change adds unit test coverage

- [x] This change adds integration test coverage

- [x] This change has been tested on the latest version of the platform/language or why not

### Checklist

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)

- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)

- [x] All existing and new tests complete without errors

2024-09-20 05:26 UTC, nandan-bhat submitted a review, later dismissed
Looks good to me.

2024-09-23 07:12 UTC, frederikprijck requested changes

2024-09-23 07:12 UTC, frederikprijck commented on src/Auth0.ManagementApi/Models/OrganizationCreateInvitationRequest.cs
> +        public bool SendInvitationEmail { get; set; } = true;
As mentioned in slack, we should not provide any default value. Instead we should rely on the default value on the API.

```suggestion
        public bool? SendInvitationEmail { get; set; }
```

2024-09-23 07:12 UTC, frederikprijck commented on tests/Auth0.ManagementApi.IntegrationTests/OrganizationTests.cs
> +                Assert.True(invitationRequest.SendInvitationEmail, "SendInvitationEmail should be True by default");
We need to remove this again.

2024-09-25 10:48 UTC, frederikprijck approved these changes

2024-09-25 10:54 UTC, merged